server:
 port: 9250

spring:
 datasource:

  url: jdbc:mysql://localhost:3306/miam
  username: root
  password:

  driver-class-name: com.mysql.cj.jdbc.Driver


 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    format_sql: true
  database: mysql
  database-platform: org.hibernate.dialect.MySQL8Dialect

 servlet:
  multipart:
   max-file-size: 10MB
   max-request-size: 10MB


logging:
 level:
  org:
   springframework:
    security:
     access: DEBUG

application:
 security:
  jwt:
   secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
   expiration: 86400000 # a day
   refresh-token:
     expiration: 604800000 # 7 days